### ISSUE TITLE
jedi:goto-definition returns "Definition not found" in specific case

### ISSUE THREAD

**Issue by dmalyuta** [tkf/emacs-jedi#281] opened 2017-02-25 07:11 UTC
### Issue

`jedi:goto-definition` is able to go to system functions as well as to certain project-defined custom functions, however some project-defined functions cannot be found (`Definition not found.` is returned).

### Steps to reproduce

 1. Use the following [~/.emacs.d/init.el](https://github.com/wernerandrew/jedi-starter/blob/master/jedi-starter.el)
 2. `sudo apt-get install python-pip`
 3. `sudo pip install virtualenv`
 4. `cd ~ && git clone https://github.com/ethz-asl/kalibr`
 5. Open Emacs, open file `~/kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py` and be sure that `M-x jedi:install-server` has been run before.
 6. Place cursor at [line 49](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py#L49) inside the substring `addDesignVariables` and do `M-x jedi:goto-definition`
 7. This returns `Definition not found.` in the minibuffer, yet this function is defined in the [IccSensors.py](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccSensors.py#L316) file, which is in the same directory and is imported in the module's [\_\_init\_\_.py](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/__init__.py) (which is in the same directory also and is supposedly handled by the `ini.el` file that is being used).

A simpler example of the same failure is the following **(bad example, this actually works)**:

- In file `~/test/main.py`:
```
import second as s

def foo(arg):
    arg.helloWorld()

foo(s)
```
- In file `~/test/second.py`:
```

def helloWorld():
    print("Hello World!")
```

This program runs fine (`python ~/test/main.py` outputs `Hello World!`) but running `jedi:goto-definition` on the `helloWorld` in `arg.helloWorld()` gives `Definition not found.`. However, if I were to change `main.py` directly to:
```
import second as s

s.helloWorld()
```
Now `jedi:goto-definition` works and jumps to the `def helloWorld()` in `second.py`! So it looks to be a problem with Jedi not recognizing `arg` as coming from `s`?

### Versions

 - Emacs: 24.5.1
 - OS: Ubuntu 14.04
 - Python: 2.7.6

### Expected behaviour

`jedi:goto-definition` should be able to find and go to the definition of the `addDesignVariables` function (which is one of the several project-defined functions that Jedi is returning `Definition not found.` for - you can the others also in the IccCalibrator.py file by trying out `M-x jedi:goto-definition` on them).

#### Output of ``M-x jedi:show-setup-info`

```
;; Emacs Lisp version:
(:emacs-version "24.5.1" :jedi-version "0.2.7" :python-environment-version "0.0.2alpha0")
;; Python version:
(:timeout nil)
;; Command line:
(:virtualenv "/usr/local/bin/virtualenv" :virtualenv-version "15.1.0\n")
;; Customization:
((jedi:complete-on-dot . t)
 (jedi:doc-display-buffer . display-buffer)
 (jedi:doc-hook view-mode)
 (jedi:doc-mode . rst-mode)
 (jedi:environment-root)
 (jedi:environment-virtualenv)
 (jedi:get-in-function-call-delay . 10000000)
 (jedi:get-in-function-call-timeout . 3000)
 (jedi:goto-definition-config
  (nil nil nil)
  (t nil nil)
  (nil definition nil)
  (t definition nil)
  (nil nil t)
  (t nil t)
  (nil definition t)
  (t definition t))
 (jedi:goto-definition-marker-ring-length . 16)
 (jedi:imenu-create-index-function . jedi:create-nested-imenu-index)
 (jedi:import-python-el-settings . t)
 (jedi:install-imenu)
 (jedi:install-python-jedi-dev-command "pip" "install" "--upgrade" "git+https://github.com/davidhalter/jedi.git@dev#egg=jedi")
 (jedi:key-complete .
		    [C-tab])
 (jedi:key-goto-definition .
			   [67108910])
 (jedi:key-goto-definition-pop-marker .
				      [67108908])
 (jedi:key-related-names . "r")
 (jedi:key-show-doc . "d")
 (jedi:server-args)
 (jedi:server-command "/home/danylo/.emacs.d/.python-environments/default/bin/jediepcserver")
 (jedi:setup-keys)
 (jedi:tooltip-method pos-tip popup)
 (jedi:use-shortcuts)
 (python-environment-default-root-name . "default")
 (python-environment-directory . "~/.emacs.d/.python-environments")
 (python-environment-virtualenv "virtualenv" "--system-site-packages" "--quiet"))
```

**Comment by dmalyuta** [comment] 2017-02-28 08:48
So? Anything to suggest about this issue?

**Comment by syohex** [comment] 2017-02-28 10:47
![jedi-goto-definition](https://cloud.githubusercontent.com/assets/554281/23402354/8fff4d26-fdee-11e6-8592-42bd5a2c023d.gif)

I cannot reproduce this issue. Could you try whether your jedi works as expected as below ?

```
% ipython
In [1]: import jedi

In [2]: source = '''import second as s
   ...: 
   ...: def foo(arg):
   ...:     arg.helloWorld()
   ...:     
   ...: foo(s)
   ...: '''

In [3]: script = jedi.Script(source, 4, len('    arg.'), 'main.py')

In [4]: defs = script.goto_definitions()

In [5]: defs
Out[5]: [<Definition def helloWorld>]

In [6]: defs[0].line
Out[6]: 1
```

**Comment by dmalyuta** [comment] 2017-02-28 17:03
Sorry, in fact the example I provided works, as well as a few other examples that try to reproduce the code structure of [this code which I encountered the original problem with](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py#L49).  So I think we should focus on fixing the issue Jedi is having with this code - perhaps it is a new bug. Do this:

1. Clone [this repository](https://github.com/ethz-asl/kalibr): `git clone https://github.com/ethz-asl/kalibr`
2. Go to [line 49](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py#L49) and place cursor inside `addDesignVariables`.
 3. Do `M-x jedi:goto-definition`, which returns `Definition not found.`

Fair enough... I do not know why this happens, but also I notice that IccSensors.py, where `addDesignVariables` is defined, is not imported, so I add the following line at the top of the [file](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py):
```
import IccSensors as mysens
```
Now I type the following in this same file, just above the `def addSplineDesignVariables` on [line 19](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py#L19):
```
mysens.<M-x jedi:goto-definition>
```
A curious thing happened: I initially could not see the word `class` for `IccImu` and `IccCamera` in the autocomplete window, but when I deleted the `()` after the class names in the IccSensors.py file, then I could see them. But once I fixed this issue, it seems like I do not get this issue anymore, even when I add back the parentheses (but is this symptomatic of something, like python version?). Anyway, now when I finish the line and type:
```
mysens.IccCameraChain.addDesignVariables(<stuff>)
```
then `M-x jedi:goto-definition` works on the `addDesignVariables`. However, I still get `Definition not found.` for [line 49](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py#L49).

What can you say about this issue/how to fix it/whether this is fundamentally impossible and I have to just do grep searches for these edge cases in order to find the functions? It seems to me like Jedi should be parsing the whole set of Python files and see where functions are called and with what argument types, which would narrow the number of possible corresponding function definitions - which can then be output in the selection list.

**Comment by syohex** [comment] 2017-03-01 02:48
Could you test without Emacs ? We should consider what cause is this issue, `jedi`(Python library) itself or this emacs package. If `jedi` cannot get definition information in your case, it is jedi issue, not this emacs package. 

> 1. Clone this repository: git clone https://github.com/ethz-asl/kalibr
> 2. Go to line 49 and place cursor inside addDesignVariables.
> 3. Do M-x jedi:goto-definition, which returns Definition not found.

I cannot get any information in your case.

```
% ipython
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import jedi

In [2]: source = open('IccCalibrator.py', 'r').read()

In [3]: script = jedi.Script(source, 49, len('        self.CameraChain.'), 'IccCalibrator.py')

In [4]: defs = script.goto_definitions()

In [5]: defs
Out[5]: []
```

**Comment by dmalyuta** [comment] 2017-03-01 02:56
So do you mean that this is a Jedi issue, since you cannot get any information by using Jedi directly at the console?

**Comment by syohex** [comment] 2017-03-01 03:08
Yes, I think. `jedi.el` uses `jedi` results. So `jedi` does not return any results, then `jedi.el` cannot do anything.

**Comment by wuliuxiansheng** [comment] 2018-06-26 00:06
What I usually do for this case is that I add an extra line to assert the type of the variable. For example, in your case, add `assert isinstance(args, s)` before using args. Then `jedi` can do its job well.

**Comment by immerrr** [comment] 2018-11-07 11:41
If that's happening to a function parameter, you can also help Jedi with a type annotation, ie.
```
def foo(x: str):
    ...
```
or a sphinx-like docstring
```
def foo(x):
    """
    :type x: str
    """
```

I believe there's nothing to fix about this in emacs-jedi, so I'm closing this.

**Closed by immerrr** 2018-11-07 11:41 UTC
